server.port=9001

file-server.driver=LOCAL

# AWS Config
file-server.aws-s3.access-key=
file-server.aws-s3.secret-key=
file-server.aws-s3.region=
file-server.aws-s3.bucket=

logging.level.org.springframework.web= DEBUG
logging.level.org.hibernate= ERROR

# Data source
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/homesecurity
spring.datasource.username=homesecurity
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
